version: 2.1

executors:
  default-executor:
    docker:
      - image: "cimg/node:lts"
    working_directory: ~/project
    resource_class: medium

commands:
  restore_test_cache:
    steps:
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
  save_test_cache:
    steps:
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  setup:
    steps:
      - run:
          name: Setup
          command: |
            npm install
            npm update
            npm prune
  test:
    steps:
      - run:
          name: Test
          command: |
            npm run test

jobs:
  build-and-test:
    executor: default-executor
    steps:
      - checkout
      - restore_test_cache
      - setup
      - save_test_cache
      - test

workflows:
  build-and-test-workflow:
    when:
      not:
        or:
          - equal: [ master, <<pipeline.git.branch>> ]
          - equal: [ develop, <<pipeline.git.branch>> ]
          - matches: { pattern: "^hotfix.*", value: <<pipeline.git.branch>> }
          - matches: { pattern: "^release.*", value: <<pipeline.git.branch>> }
    jobs:
      - build-and-test
